import { buildDepTree } from '../lib';

const exampleVendorJson = `{
	"comment": "v1.2",
	"ignore": "",
	"rootPath": "github.com/snyk/awesomegoproject",
	"package": [
		{
			"checksumSHA1": "dummy",
			"path": "gitpub.com/food/salad",
			"revision": "8b100cedd15d96a9ba0f4e48fd852d21b93b0f33",
			"versionExact": "v1.3.7"
		},
		{
			"checksumSHA1": "dummy",
			"path": "gitpub.com/nature/vegetables/tomato",
			"revision": "b6ffb7d62206806b573348160795ea16a00940a6"
		},
		{
			"checksumSHA1": "dummy",
			"path": "gitpub.com/nature/vegetables/cucamba",
			"revision": "b6ffb7d62206806b573348160795ea16a00940a6"
		},
		{
			"checksumSHA1": "dummy",
			"path": "gitpub.com/meal/dinner",
			"revision": "2ebf14b5ac2969032b6c7f6f3e9ff1b2a8db0075",
			"versionExact": "v0.0.7"
		}
	]
}`

it('govendor parsing works', async () => {
	expect(await buildDepTree(exampleVendorJson, '', 'govendor')).toEqual(
		{
			name: 'github.com/snyk/awesomegoproject',
			version: '0.0.0',
			dependencies: {
				'gitpub.com/food/salad': {
					name: 'gitpub.com/food/salad',
					version: 'v1.3.7',
				},
				"gitpub.com/meal/dinner": {
					"name": "gitpub.com/meal/dinner",
					"version": "v0.0.7",
				},
				"gitpub.com/nature/vegetables/cucamba": {
					"name": "gitpub.com/nature/vegetables/cucamba",
					"version": "#b6ffb7d62206806b573348160795ea16a00940a6",
				},
				"gitpub.com/nature/vegetables/tomato": {
					"name": "gitpub.com/nature/vegetables/tomato",
					"version": "#b6ffb7d62206806b573348160795ea16a00940a6",
				},
			},
		}
);
});

const exampleDep = {
	lock: `# this file should be autogenerated, but instead was crafted with love

	[[projects]]
	  name = "gitpub.com/food/salad"
	  packages = ["."]
	  revision = "8b100cedd15d96a9ba0f4e48fd852d21b93b0f33"
	  version = "v1.3.7"

	[[projects]]
	  name = "gitpub.com/nature/vegetables"
	  packages = ["tomato", "cucamba"]
	  revision = "b6ffb7d62206806b573348160795ea16a00940a6"

	[[projects]]
	  name = "gitpub.com/meal/dinner"
	  packages = ["."]
	  revision = "2ebf14b5ac2969032b6c7f6f3e9ff1b2a8db0075"
	  version = "v0.0.7"

	`,
	manifest: ``,
}

it('dep parsing works', async () => {
	expect(await buildDepTree(exampleDep.manifest, exampleDep.lock, 'golangdep')).toEqual(
		{
			name: 'root',
			version: '0.0.0',
			dependencies: {
				'gitpub.com/food/salad': {
					name: 'gitpub.com/food/salad',
					version: 'v1.3.7',
				},
				"gitpub.com/meal/dinner": {
					"name": "gitpub.com/meal/dinner",
					"version": "v0.0.7",
				},
				"gitpub.com/nature/vegetables/cucamba": {
					"name": "gitpub.com/nature/vegetables/cucamba",
					"version": "#b6ffb7d62206806b573348160795ea16a00940a6",
				},
				"gitpub.com/nature/vegetables/tomato": {
					"name": "gitpub.com/nature/vegetables/tomato",
					"version": "#b6ffb7d62206806b573348160795ea16a00940a6",
				},
			},
		}
);
});
