version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/node:20.19.3
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    docker:
      - image: cimg/node:20.19.3
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  release:
    docker:
      - image: cimg/node:20.19.3
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@17

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-sca
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context: open_source-managed

      - test:
          name: Test

      - release:
          name: Release
          requires:
            - Test
            - Security Scans
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
