version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1.0

jobs:
  test:
    docker:
      - image: cimg/node:14.19
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
  release:
    docker:
      - image: cimg/node:14.19
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Release
          command: npx semantic-release@17

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
      - test:
          name: Test
      - release:
          name: Release
          requires:
            - Test
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
